### ISSUE TITLE
Vuetify Components are not recognized by Vitest

### ISSUE THREAD

**Issue by JuHardtung** [TMink/Digitales-3D-Feldbuch-Projekt-2-#115]
![NVIDIA_Share_wwXpxgZx8X](https://github.com/TMink/Digitales-3D-Feldbuch-Projekt-2-/assets/15029310/1751bdd5-e6cc-463c-9dbf-370b67ed0fe4)

**Comment by Methusshan25** [comment]
I pushed now an new Version of the vitest.config.js and the vite.config.js. This should solve the problem. And you should install all dependencies, because a new dependency called "resize-observer-polyfill" was required to solve the problem.

Then the tests should look like this
![image](https://github.com/TMink/Digitales-3D-Feldbuch-Projekt-2-/assets/56478334/28f27c55-af10-45a8-80f9-4dc0b4119b16)

**Comment by JuHardtung** [comment]
Yes, the updated config files fixed the issue. It is now working as intended
